@startuml

 class 你 {
  - 9快9包邮的大苹果,要不要
  - 到处爆满,嗨毛线,晚上回家
 }

 class 她{
 -小抠鼻,一个苹果都不给我
 -我想买...
 -我想玩...
 }

 class 朋友{
  -有钱任性，想买啥买啥
 }
 你 <-- 她  : 圣诞要礼物
 你 --> 朋友 :鄙视收礼物还发朋友圈的
 她 -> 朋友 : 羡慕人家的礼物

@enduml